name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # or 'main' depending on your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t yourusername/your-image-name:latest .

      - name: Push Docker image
        run: docker push yourusername/your-image-name:latest
